[package]
name = "jump-jump"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_hanabi = "0.10"
rand = "0.8.0"
bevy = { version = "0.13.2", features = ["mp3"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "= 0.2.91" }
